---
title: "Final Project Rubric"
output: html_notebook
---

- [15 points] Data Access
(1) Analysis includes at least two different data tables. 
(2) Primary data table may NOT be loaded from an R package--though supporting data may. 
(3) Access to all data is contained within the analysis. (Each data source must be included in the provided GitHub Repo & properly accessed in the Rmd (e.g., read_csv() or other means)
(4) Data intake is inspected properly at beginning of analysis -- e.g. use at least one of str(), glimpse(), head(), etc.

- [40 points] Data Wrangling / Processing / etc
Students need not use every function and method introduced in STAT 184, but clear demonstration of proficiency should include proper use of at least 5 of these 8 topics from class: 

(1) general data wrangling using various data verbs like filter, mutate, summarise, arrange, group_by, etc. 
(2) joins for multiple data tables
(3) reduction and/or transformation functions like mean, sum, max, min, n(), rank, pmin, etc. 
(4) pivot_wider & pivot_longer --or similar function to stack/unstack variables 
(5) regular expressions 
(6) user-defined functions 
(7) loops/control flow
(8) for use of machine learning (not "wrangling" but scored here)

- [40 points] 	This criterion is linked to a Learning Outcome Data Visualization
Students need not use every function and method introduced in STAT 184, but clear demonstration of proficiency should include data visualizations that 
(*1*) are relevant to stated research question for the analysis,
(*2*) appear professional by including titles, axis labels, guides, etc
(*3*) include at least one effective display of two or more variables, 
(*4*) use of multiple geoms such as points, density, lines, boxplots, etc,
(*5*) use of multiple aesthetics--not necessarily all in the same graph--such as color, size, shape, x/y position, facets, alpha, etc 

Optional add-ons:
(+) layered graphics such as points and accompanying smoother, points and accompanying boxplots, overlaid density distributions, etc (+) leaflet or choropleth maps (+) decision tree and/or dendogram displaying exploratory machine learning results

- [15 points] Code Quality
Code formatting is consistent with Style Guide Appendix of DataComputing eBook. Specifically, all code chunks demonstrate proficiency with (1) meaningful object names (2) proper use of spacing and new lines (3) use of meaningful comments.

- [15 points] 	This criterion is linked to a Learning Outcome Narrative Quality
The narrative text--sentences and paragraphs--
(1) clearly states one guiding question or research question for your investigation 
(2) explains why this topic is important and/or interesting to investigate 
(3) explains one or more significant findings or conclusions of your investigation that is clearly related to the guiding/research question

- [15 points] 	This criterion is linked to a Learning Outcome Overall Quality
(1) Submitted project shows significant effort to produce a high-quality and thoughtful analysis that contains interpretation of plots and other output 
(2) The analysis is well-organized and easy to follow, and 
(3) Free of extraneous content - examples: do NOT output full data frames of >20 rows, any unrelated graphs, or other content with unclear purpose

- [15 points] GitHub Repo
(1) At least 3 commits pushed to provided GitHub repo PER person
(2) All commits must have an informative commit message that summarizes the contribution 
(3) Final project is entirely contained in the provided repo, including data sources, documents, and anything else that another analyst would need to reproduce your entire analysis (e.g. do NOT make any references to your personal desktop like C:\Users\Olivia\STAT184)